//See Trigger tab to adjust its distance if (( ( ( ( dist ) < ( 250 ) ) Change this value to adjust the distance in  250 cm - TFMini has a range of 1200cm

void trigger(){


  
    if (( ( ( ( dist ) < ( 250 ) ) && ( ( dist ) > ( 5 ) ) ) && ( ( ( 5 * 	ardublockUltrasonicSensorCodeAutoGeneratedReturnCM( 4 , 4 ) ) ) > ( 100 ) ) ))
    {
      servo_pin_3.write( 130 );
      delay( 300 );
    }
  }
